# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: dev
    http:
        encoding:
            charset: UTF-8 # the encoding of HTTP requests/responses
            enabled: true # enable http encoding support
            force: true # force the configured encoding
    cloud:
        config:
            server:
                native:
                    search-locations: file:./central-config
                prefix: /config
