# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: prod
    http:
        encoding:
            charset: UTF-8 # the encoding of HTTP requests/responses
            enabled: true # enable http encoding support
            force: true # force the configured encoding
    cloud:
        config:
            server:
                git:
                    # sample prod config using the central-directory folder in the max-registry github repos
                    uri: https://github.com/jhulick/max-registry/
                    search-paths: central-config
                prefix: /config

