server:
    port: 8200

spring:
    profiles:
        active: docker
    http:
        encoding:
            charset: UTF-8 # the encoding of HTTP requests/responses
            enabled: true  # enable http encoding support
            force: true    # force the configured encoding
    redis:
        host: localhost
        port: 6379
        default_expire_time: 86400

logging:
    level:
        org.springframework.security: TRACE
    file: gateway-docker.log

zuul:
    routes:
        ui:
            url: http://ui:8081
        resource:
            url: http://resource:9005

server.address: 0.0.0.0 # needed by docker networking - do not use localhost or 127.0.0.1

token.secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==

app:
    admin.userName: admin
    service:
        security: http://localhost:18200/login/cas
        home: http://localhost:18200/
cas:
    url.prefix: http://cas:9002/cas/
    service:
        login: ${cas.url.prefix}/login
        logout: ${cas.url.prefix}/logout
        rest: ${cas.url.prefix}/rv1/tickets

